# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pokemonPicker.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 181, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 202, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(206, 92, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 181, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 202, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(184, 181, 178))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 202, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(180, 202, 242))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayoutMain = QtWidgets.QVBoxLayout()
        self.verticalLayoutMain.setObjectName("verticalLayoutMain")
        self.verticalLayoutTop = QtWidgets.QVBoxLayout()
        self.verticalLayoutTop.setObjectName("verticalLayoutTop")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frameParameters = QtWidgets.QFrame(self.centralwidget)
        self.frameParameters.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameParameters.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameParameters.setObjectName("frameParameters")
        self.labelParameters = QtWidgets.QLabel(self.frameParameters)
        self.labelParameters.setGeometry(QtCore.QRect(120, 10, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(14)
        self.labelParameters.setFont(font)
        self.labelParameters.setObjectName("labelParameters")
        self.checkLegends = QtWidgets.QCheckBox(self.frameParameters)
        self.checkLegends.setGeometry(QtCore.QRect(90, 40, 158, 23))
        self.checkLegends.setObjectName("checkLegends")
        self.checkRepetitions = QtWidgets.QCheckBox(self.frameParameters)
        self.checkRepetitions.setGeometry(QtCore.QRect(90, 60, 142, 23))
        self.checkRepetitions.setObjectName("checkRepetitions")
        self.checkFullyEvolved = QtWidgets.QCheckBox(self.frameParameters)
        self.checkFullyEvolved.setGeometry(QtCore.QRect(90, 80, 252, 23))
        self.checkFullyEvolved.setObjectName("checkFullyEvolved")
        self.horizontalLayout.addWidget(self.frameParameters)
        self.frameGenerations = QtWidgets.QFrame(self.centralwidget)
        self.frameGenerations.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameGenerations.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameGenerations.setObjectName("frameGenerations")
        self.labelGenerations = QtWidgets.QLabel(self.frameGenerations)
        self.labelGenerations.setGeometry(QtCore.QRect(140, 10, 118, 23))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(14)
        self.labelGenerations.setFont(font)
        self.labelGenerations.setObjectName("labelGenerations")
        self.checkGen1 = QtWidgets.QCheckBox(self.frameGenerations)
        self.checkGen1.setGeometry(QtCore.QRect(70, 40, 34, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkGen1.setFont(font)
        self.checkGen1.setObjectName("checkGen1")
        self.checkGen2 = QtWidgets.QCheckBox(self.frameGenerations)
        self.checkGen2.setGeometry(QtCore.QRect(140, 40, 34, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkGen2.setFont(font)
        self.checkGen2.setObjectName("checkGen2")
        self.checkGen3 = QtWidgets.QCheckBox(self.frameGenerations)
        self.checkGen3.setGeometry(QtCore.QRect(200, 40, 34, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkGen3.setFont(font)
        self.checkGen3.setObjectName("checkGen3")
        self.checkGen4 = QtWidgets.QCheckBox(self.frameGenerations)
        self.checkGen4.setGeometry(QtCore.QRect(260, 40, 34, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkGen4.setFont(font)
        self.checkGen4.setObjectName("checkGen4")
        self.checkGen5 = QtWidgets.QCheckBox(self.frameGenerations)
        self.checkGen5.setGeometry(QtCore.QRect(70, 70, 34, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkGen5.setFont(font)
        self.checkGen5.setObjectName("checkGen5")
        self.checkGen6 = QtWidgets.QCheckBox(self.frameGenerations)
        self.checkGen6.setGeometry(QtCore.QRect(140, 70, 34, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkGen6.setFont(font)
        self.checkGen6.setObjectName("checkGen6")
        self.checkGen7 = QtWidgets.QCheckBox(self.frameGenerations)
        self.checkGen7.setGeometry(QtCore.QRect(200, 70, 34, 23))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.checkGen7.setFont(font)
        self.checkGen7.setObjectName("checkGen7")
        self.checkAllGen = QtWidgets.QCheckBox(self.frameGenerations)
        self.checkAllGen.setGeometry(QtCore.QRect(280, 10, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkAllGen.setFont(font)
        self.checkAllGen.setObjectName("checkAllGen")
        self.horizontalLayout.addWidget(self.frameGenerations)
        self.verticalLayoutTop.addLayout(self.horizontalLayout)
        self.frameTypes = QtWidgets.QFrame(self.centralwidget)
        self.frameTypes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTypes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTypes.setObjectName("frameTypes")
        self.labelTypes = QtWidgets.QLabel(self.frameTypes)
        self.labelTypes.setGeometry(QtCore.QRect(360, 10, 57, 23))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(14)
        self.labelTypes.setFont(font)
        self.labelTypes.setObjectName("labelTypes")
        self.checkNormal = QtWidgets.QCheckBox(self.frameTypes)
        self.checkNormal.setGeometry(QtCore.QRect(460, 40, 76, 23))
        self.checkNormal.setObjectName("checkNormal")
        self.checkWater = QtWidgets.QCheckBox(self.frameTypes)
        self.checkWater.setGeometry(QtCore.QRect(590, 80, 67, 23))
        self.checkWater.setObjectName("checkWater")
        self.checkIce = QtWidgets.QCheckBox(self.frameTypes)
        self.checkIce.setGeometry(QtCore.QRect(330, 100, 45, 23))
        self.checkIce.setObjectName("checkIce")
        self.checkPoison = QtWidgets.QCheckBox(self.frameTypes)
        self.checkPoison.setGeometry(QtCore.QRect(460, 60, 71, 23))
        self.checkPoison.setObjectName("checkPoison")
        self.checkGround = QtWidgets.QCheckBox(self.frameTypes)
        self.checkGround.setGeometry(QtCore.QRect(330, 80, 76, 23))
        self.checkGround.setObjectName("checkGround")
        self.checkFlying = QtWidgets.QCheckBox(self.frameTypes)
        self.checkFlying.setGeometry(QtCore.QRect(210, 100, 66, 23))
        self.checkFlying.setObjectName("checkFlying")
        self.checkPsychic = QtWidgets.QCheckBox(self.frameTypes)
        self.checkPsychic.setGeometry(QtCore.QRect(460, 80, 75, 23))
        self.checkPsychic.setObjectName("checkPsychic")
        self.checkFairy = QtWidgets.QCheckBox(self.frameTypes)
        self.checkFairy.setGeometry(QtCore.QRect(210, 40, 59, 23))
        self.checkFairy.setObjectName("checkFairy")
        self.checkRock = QtWidgets.QCheckBox(self.frameTypes)
        self.checkRock.setGeometry(QtCore.QRect(460, 100, 59, 23))
        self.checkRock.setObjectName("checkRock")
        self.checkSteel = QtWidgets.QCheckBox(self.frameTypes)
        self.checkSteel.setGeometry(QtCore.QRect(590, 60, 60, 23))
        self.checkSteel.setObjectName("checkSteel")
        self.checkGhost = QtWidgets.QCheckBox(self.frameTypes)
        self.checkGhost.setGeometry(QtCore.QRect(330, 40, 66, 23))
        self.checkGhost.setObjectName("checkGhost")
        self.checkBug = QtWidgets.QCheckBox(self.frameTypes)
        self.checkBug.setGeometry(QtCore.QRect(80, 40, 52, 23))
        self.checkBug.setObjectName("checkBug")
        self.checkElectric = QtWidgets.QCheckBox(self.frameTypes)
        self.checkElectric.setGeometry(QtCore.QRect(80, 100, 76, 23))
        self.checkElectric.setObjectName("checkElectric")
        self.checkDark = QtWidgets.QCheckBox(self.frameTypes)
        self.checkDark.setGeometry(QtCore.QRect(80, 60, 57, 23))
        self.checkDark.setObjectName("checkDark")
        self.checkFire = QtWidgets.QCheckBox(self.frameTypes)
        self.checkFire.setGeometry(QtCore.QRect(210, 80, 51, 23))
        self.checkFire.setObjectName("checkFire")
        self.checkGrass = QtWidgets.QCheckBox(self.frameTypes)
        self.checkGrass.setGeometry(QtCore.QRect(330, 60, 63, 23))
        self.checkGrass.setObjectName("checkGrass")
        self.checkFighting = QtWidgets.QCheckBox(self.frameTypes)
        self.checkFighting.setGeometry(QtCore.QRect(210, 60, 82, 23))
        self.checkFighting.setObjectName("checkFighting")
        self.checkDragon = QtWidgets.QCheckBox(self.frameTypes)
        self.checkDragon.setGeometry(QtCore.QRect(80, 80, 76, 23))
        self.checkDragon.setObjectName("checkDragon")
        self.checkAllTypes = QtWidgets.QCheckBox(self.frameTypes)
        self.checkAllTypes.setGeometry(QtCore.QRect(470, 10, 91, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.checkAllTypes.setFont(font)
        self.checkAllTypes.setObjectName("checkAllTypes")
        self.verticalLayoutTop.addWidget(self.frameTypes)
        self.verticalLayoutMain.addLayout(self.verticalLayoutTop)
        self.generateButton = QtWidgets.QPushButton(self.centralwidget)
        self.generateButton.setEnabled(True)
        self.generateButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.generateButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.generateButton.setObjectName("generateButton")
        self.verticalLayoutMain.addWidget(self.generateButton)
        self.frameTeam = QtWidgets.QFrame(self.centralwidget)
        self.frameTeam.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTeam.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTeam.setObjectName("frameTeam")
        self.labelTeam = QtWidgets.QLabel(self.frameTeam)
        self.labelTeam.setGeometry(QtCore.QRect(350, 10, 81, 33))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelTeam.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.labelTeam.setFont(font)
        self.labelTeam.setObjectName("labelTeam")
        self.labelPokemon1 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokemon1.setGeometry(QtCore.QRect(80, 80, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokemon1.setFont(font)
        self.labelPokemon1.setObjectName("labelPokemon1")
        self.labelPokemon2 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokemon2.setGeometry(QtCore.QRect(80, 120, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokemon2.setFont(font)
        self.labelPokemon2.setObjectName("labelPokemon2")
        self.labelPokemon3 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokemon3.setGeometry(QtCore.QRect(80, 160, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokemon3.setFont(font)
        self.labelPokemon3.setObjectName("labelPokemon3")
        self.labelPokemon4 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokemon4.setGeometry(QtCore.QRect(400, 80, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokemon4.setFont(font)
        self.labelPokemon4.setObjectName("labelPokemon4")
        self.labelPokemon5 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokemon5.setGeometry(QtCore.QRect(400, 120, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokemon5.setFont(font)
        self.labelPokemon5.setObjectName("labelPokemon5")
        self.labelPokemon6 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokemon6.setGeometry(QtCore.QRect(400, 160, 111, 22))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokemon6.setFont(font)
        self.labelPokemon6.setObjectName("labelPokemon6")
        self.labelPokeName1 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokeName1.setGeometry(QtCore.QRect(200, 80, 161, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelPokeName1.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labelPokeName1.setFont(font)
        self.labelPokeName1.setText("")
        self.labelPokeName1.setObjectName("labelPokeName1")
        self.labelPokeName2 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokeName2.setGeometry(QtCore.QRect(200, 120, 161, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelPokeName2.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokeName2.setFont(font)
        self.labelPokeName2.setText("")
        self.labelPokeName2.setObjectName("labelPokeName2")
        self.labelPokeName3 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokeName3.setGeometry(QtCore.QRect(200, 160, 161, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelPokeName3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokeName3.setFont(font)
        self.labelPokeName3.setText("")
        self.labelPokeName3.setObjectName("labelPokeName3")
        self.labelPokeName4 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokeName4.setGeometry(QtCore.QRect(520, 80, 181, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelPokeName4.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokeName4.setFont(font)
        self.labelPokeName4.setText("")
        self.labelPokeName4.setObjectName("labelPokeName4")
        self.labelPokeName5 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokeName5.setGeometry(QtCore.QRect(520, 120, 181, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelPokeName5.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokeName5.setFont(font)
        self.labelPokeName5.setText("")
        self.labelPokeName5.setObjectName("labelPokeName5")
        self.labelPokeName6 = QtWidgets.QLabel(self.frameTeam)
        self.labelPokeName6.setGeometry(QtCore.QRect(520, 160, 181, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelPokeName6.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPokeName6.setFont(font)
        self.labelPokeName6.setText("")
        self.labelPokeName6.setObjectName("labelPokeName6")
        self.labelError = QtWidgets.QLabel(self.frameTeam)
        self.labelError.setGeometry(QtCore.QRect(90, 200, 622, 32))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelError.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelError.setFont(font)
        self.labelError.setText("")
        self.labelError.setObjectName("labelError")
        self.verticalLayoutMain.addWidget(self.frameTeam)
        self.verticalLayout.addLayout(self.verticalLayoutMain)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pokemon Picker v1.0"))
        self.labelParameters.setText(_translate("MainWindow", "Parameters"))
        self.checkLegends.setText(_translate("MainWindow", "Include legendaries"))
        self.checkRepetitions.setText(_translate("MainWindow", "Allow repetitions"))
        self.checkFullyEvolved.setText(_translate("MainWindow", "Show only fully evolved pokemon"))
        self.labelGenerations.setText(_translate("MainWindow", "Generations"))
        self.checkGen1.setText(_translate("MainWindow", "1"))
        self.checkGen2.setText(_translate("MainWindow", "2"))
        self.checkGen3.setText(_translate("MainWindow", "3"))
        self.checkGen4.setText(_translate("MainWindow", "4"))
        self.checkGen5.setText(_translate("MainWindow", "5"))
        self.checkGen6.setText(_translate("MainWindow", "6"))
        self.checkGen7.setText(_translate("MainWindow", "7"))
        self.checkAllGen.setText(_translate("MainWindow", "All/none"))
        self.labelTypes.setText(_translate("MainWindow", "Types"))
        self.checkNormal.setText(_translate("MainWindow", "Normal"))
        self.checkWater.setText(_translate("MainWindow", "Water"))
        self.checkIce.setText(_translate("MainWindow", "Ice"))
        self.checkPoison.setText(_translate("MainWindow", "Poison"))
        self.checkGround.setText(_translate("MainWindow", "Ground"))
        self.checkFlying.setText(_translate("MainWindow", "Flying"))
        self.checkPsychic.setText(_translate("MainWindow", "Psychic"))
        self.checkFairy.setText(_translate("MainWindow", "Fairy"))
        self.checkRock.setText(_translate("MainWindow", "Rock"))
        self.checkSteel.setText(_translate("MainWindow", "Steel"))
        self.checkGhost.setText(_translate("MainWindow", "Ghost"))
        self.checkBug.setText(_translate("MainWindow", "Bug"))
        self.checkElectric.setText(_translate("MainWindow", "Electric"))
        self.checkDark.setText(_translate("MainWindow", "Dark"))
        self.checkFire.setText(_translate("MainWindow", "Fire"))
        self.checkGrass.setText(_translate("MainWindow", "Grass"))
        self.checkFighting.setText(_translate("MainWindow", "Fighting"))
        self.checkDragon.setText(_translate("MainWindow", "Dragon"))
        self.checkAllTypes.setText(_translate("MainWindow", "All/none"))
        self.generateButton.setText(_translate("MainWindow", "Generate Team!"))
        self.labelTeam.setText(_translate("MainWindow", "Team"))
        self.labelPokemon1.setText(_translate("MainWindow", "Pokémon 1 - "))
        self.labelPokemon2.setText(_translate("MainWindow", "Pokémon 2 - "))
        self.labelPokemon3.setText(_translate("MainWindow", "Pokémon 3 - "))
        self.labelPokemon4.setText(_translate("MainWindow", "Pokémon 4 - "))
        self.labelPokemon5.setText(_translate("MainWindow", "Pokémon 5 - "))
        self.labelPokemon6.setText(_translate("MainWindow", "Pokémon 6 - "))

